### ISSUE TITLE
Threading crash

### ISSUE THREAD

**Issue by JohnnyBravo75** [AngryCarrot789/FramePFX#5]
**Describe the bug**
Hard crash because of threading issues

**To Reproduce**
i placed a short mp4 video in two tracks  and rotated and scaled them. 
When I want to place the video in a third track it crashed.

**Expected behavior**
No crash

**Screenshots**
![image](https://github.com/AngryCarrot789/FramePFX/assets/7339098/d118afb0-fd35-4f84-b214-748c0ec2be3b)

**Comment by AngryCarrot789** [comment]
Kinda fixed this in the most recent push

**Comment by AngryCarrot789** [comment]
Also it seems like you're using a really old version back when I used MVVM, I rewrote the entire code base a few months ago if you wanna check that out

**Comment by JohnnyBravo75** [comment]
Ok thanks for the quick response.
I was using the latest relase version "Release v1.0.2".
But when you fixed it in the recent version, I will close the issue and try again.
