### ISSUE TITLE
Importing audio file gives error

### ISSUE THREAD

**Issue by qayyumabro** [AngryCarrot789/FramePFX#6]
Hi, I get this error when I import mp3 file, is it supported or not?

![image](https://github.com/AngryCarrot789/FramePFX/assets/9138521/ef547a57-0641-4758-999c-655d2d75970d)

![image](https://github.com/AngryCarrot789/FramePFX/assets/9138521/f6237f48-cda5-49dd-ab25-15b7d540a3dc)

**Comment by AngryCarrot789** [comment]
Playing audio from files/videos isn't supported yet, since I still have to figure out the crackling problem (which requires a re-work of the video and audio playback engine)
